FUS: Collect Code Vision data
intellij-rust/intellij-rust pull request #10152
Opened 2023-02-20 12:24 UTC by ortem

Note, the statistics are collected only if you [explicitly allow](https://www.jetbrains.com/help/idea/settings-usage-statistics.html) it

2023-02-20 14:15 UTC, Undin requested changes

2023-02-20 14:15 UTC, Undin commented on src/main/kotlin/org/rust/ide/statistics/RsCodeVisionUsageCollector.kt
> +class RsCodeVisionUsageCollector : CounterUsagesCollector() {
You didn't register this extension, so it won't be possible to generate rules for this collector for statistics server

2023-02-20 20:37 UTC, ortem commented on src/231/main/resources/META-INF/platform-rust-core.xml
> +        implementation="org.rust.ide.hints.codeVision.RsReferenceCodeVisionProvider"/>
Funny, I just did it because IDEA shows `Cannot resolve class 'RsReferenceCodeVisionProvider'` error in the editor

2023-02-20 23:46 UTC, Undin requested changes
Tests still cannot be compiled because you moved `RsReferenceCodeVisionProvider.ID` to base class

2023-02-20 23:46 UTC, Undin commented on src/main/kotlin/org/rust/ide/statistics/RsCodeVisionUsageCollector.kt
> +        private enum class Location(name: String) {
`name` is unused. You just pass some string values and don't keep them anywhere. Yeah, in `getLocation ` you use `name` property, but it's builtin enum property

2023-02-20 23:46 UTC, Undin commented on src/main/kotlin/org/rust/ide/statistics/RsCodeVisionUsageCollector.kt
> +        )
There are `EnumEventField` and `EventFields.Enum` not to convert enums to strings manually

2023-02-20 23:49 UTC, Undin commented on src/main/kotlin/org/rust/ide/statistics/RsCodeVisionUsageCollector.kt
> +        private val USAGES_CLICKED_EVENT_ID = GROUP.registerEvent("usages.clicked", LOCATION_FIELD)
```suggestion
        private val USAGES_CLICKED_EVENT = GROUP.registerEvent("usages.clicked", LOCATION_FIELD)
```

2023-02-22 10:25 UTC, Undin approved these changes
LGTM but comment

2023-02-22 10:25 UTC, Undin commented on src/main/kotlin/org/rust/ide/statistics/RsCodeVisionUsageCollector.kt
> +        private val LOCATION_FIELD = EventFields.Enum<Location>("location")
It seems you didn't want to pass `FUNCTION` name that's why you tried to add some more human friendly names.
Actually, I liked the idea with custom names or at least make case lower. To do it, you can pass custom `transform` lambda to `EventFields.Enum` function

Currently, it looks like `"location":"FUNCTION"`

2023-02-24 00:26 UTC, Undin approved these changes
bors r+

2023-02-24 09:19 UTC, Undin commented
bors retry

2023-02-24 10:25 UTC, merged