RUN: Add build task for wasm-pack configurations
intellij-rust/intellij-rust pull request #5939
Opened 2020-08-15 19:52 UTC by avrong

Adds `Before launch` task for `wasm-pack` run configurations. Emulates the first part of wasm-pack process — executing `cargo build` with specific arguments like `--target wasm32-unknown-unknown`.

Provides a way to show cargo build tool window before `wasm-pack` packing instead of raw printing in the terminal. Also, it asks a user to install a specific target to perform build.

The implementation is mostly similar to `CargoBuildTaskProvider`, component installation in `Rustup` and `InstallComponentAction`.

Related to #3066

<img width="650" src="https://user-images.githubusercontent.com/6342851/90320255-3bac2c00-df48-11ea-893e-878832f27f34.gif">

2020-11-02 13:19 UTC, ortem requested changes

2020-11-02 13:19 UTC, ortem commented on src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
> +        val buildConfiguration = CargoCommandConfiguration(
Probably it's better to use `RunManager.getInstance(project).createConfiguration(configuration.name, CargoCommandConfigurationType::class.java)`. Also, do we need a name here, or maybe just pass an empty string as a name?

2020-11-02 13:19 UTC, ortem commented on src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
> +        val buildCommand = ParametersListUtil.join(mutableListOf("build").apply {
I'd recommend extracting a variable to have something like
```Kotlin
val parameters = ...
val buildCommand = ParametersListUtil.join(parameters)
```

2020-11-02 13:19 UTC, ortem commented on src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
> +                addIfNotPresent("--tests")
Maybe replace `linkedSetOf` with `mutableListOf` (and add `.toList()` at the end) to use `add` instead?

2020-11-02 13:20 UTC, ortem commented on src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
> +        val buildConfiguration = CargoCommandConfiguration(
I'm not sure actually, @mchernyavsky maybe you have some comments?

2020-11-05 16:21 UTC, ortem commented on src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
> +        val buildConfiguration = CargoCommandConfiguration(
@avrong Let's finally use `RunManager` here and leave the name if it is displayed in the UI somehow

2020-11-07 09:52 UTC, mchernyavsky commented on src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
> +class WasmPackBuildTaskProvider : BeforeRunTaskProvider<WasmPackBuildTaskProvider.BuildTask>() {
[Introduce_`RsBuildTaskProvider`.patch.zip](https://github.com/intellij-rust/intellij-rust/files/5504545/Introduce_.RsBuildTaskProvider.patch.zip)

2020-11-25 17:54 UTC, ortem commented
bors r+

2020-11-25 18:33 UTC, merged