INT: add support for creating methods in CreateFunctionIntention
intellij-rust/intellij-rust pull request #6039
Opened 2020-08-31 14:34 UTC by Kobzol

This PR adds support for creatng methods in `CreateFunctionIntention`. Also I previously forget to register the intention and add a description, since it was originally a quick fix, so this PR also fixes that.

![create-method](https://user-images.githubusercontent.com/4539057/91731838-ae074800-eba7-11ea-89a1-3b98d50798e8.gif)

2020-08-31 18:59 UTC, vlad20012 commented
> Also I previously forget to register the intention and add a description, since it was originally a quick fix, so this PR also fixes that.

😄 we must add some check to `RsIntentionTestBase`

2020-08-31 19:18 UTC, vlad20012 commented on src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
> +            if (methodCall.reference.resolve() != null) return null
Same as in function call case, let's limit possible caret position to the method identifier. `element == methodCall.identifier` should works

2020-08-31 19:34 UTC, Kobzol commented
>  we must add some check to `RsIntentionTestBase`

Ooh, I actually thought that it exists, I even wrote so on my blog :D But it only exists for inspections. I'll add it for intentions too.

2020-09-02 07:49 UTC, Undin requested changes
@Kobzol Let's split this PR into two: the first to fix intention registration and the second one to add new feature. It allows us to cherry-pick only fix into v130 release, put new feature into v131 (or later if something will happen) and don't change our usual workflow

2020-09-02 17:28 UTC, vlad20012 approved these changes
:+1: 
Rebase it to the latest master, please

2020-09-09 07:38 UTC, vlad20012 commented
bors r+

2020-09-09 08:54 UTC, merged