INT: Extend function argument count check to work for closures (E0057)
intellij-rust/intellij-rust pull request #6319
Opened 2020-10-28 23:16 UTC by zeroeightysix

This PR extends the intention for fixing an incorrect amount of arguments passed to a function to work for closures as well. This corresponds to rust error [E0057](https://doc.rust-lang.org/error-index.html#E0057).

This PR might clash with #6318 as both modify the same enum, on the same line.

2020-11-09 15:52 UTC, Undin requested changes

2020-11-09 15:52 UTC, Undin commented on src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
> +        is RsPatBinding -> {
Note, I can write
```rust
struct S(&'static dyn Fn(i32));

const F: &'static dyn Fn(i32) = &bar;

fn main() {
    let s = S(&bar);
    s.0(123, 123); // <- E0057 and struct field
    F(1, 2); // <- E0057 and const item
}

fn bar(x: i32) {
    println!("{}", x);
}
```

Just notice, don't insist on supporting these cases in this PR

2020-11-13 17:43 UTC, Undin commented on src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
> +            if (type is TyFunction) {
@zeroeightysix let's use some heuristic here to detect only `E0057`.
For example, let's support only case `let el = closure`, i.e. when parent of `el` is `RsLetDecl` and the corresponding expression is `RsLambdaExpr`.
And after #6391, replace the heuristic with a more generic implementation

2020-11-13 17:43 UTC, Undin commented on src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
> +        Pair(it, if (fn.isVariadic) FunctionType.VARIADIC_FUNCTION else FunctionType.FUNCTION)
nit: let's extract `if (fn.isVariadic) FunctionType.VARIADIC_FUNCTION else FunctionType.FUNCTION)` into variable

2020-11-13 20:30 UTC, zeroeightysix commented on src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
> +            if (type is TyFunction) {
I'm not sure I follow.

*E0057* only occurs in calls, right? How can this diagnostic detect E0057 in a `let el = closure` statement?

If you mean detecting the following:
```rust
let f = || ();

f(5); // <-- E0057 here
```
I'm not sure how I would inspect the declaration of `f`.

2020-11-15 10:34 UTC, Undin commented on src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
> +            if (type is TyFunction) {
> E0057 only occurs in calls, right?

Yep

> How can this diagnostic detect E0057 in a `let el = closure` statement?
>
> If you mean detecting the following:
> ```rust
> let f = || ();
>
> f(5); // <-- E0057 here
> ```
> I'm not sure how I would inspect the declaration of `f`.

You already have `el` variable that represents `f` in the described case and you can check all necessary nodes of AST here. For example, something like
```kotlin
// TODO: replace with more generic solution
// when https://github.com/intellij-rust/intellij-rust/issues/6391 will be implemented
if (type is TyFunction) {
    val letDecl = el.parent?.parent as? RsLetDecl
    if (letDecl?.expr is RsLambdaExpr) type.paramTypes.size to FunctionType.CLOSURE else null
} else {
    null
}
```
Of course, it won't detect all possible cases, for example, it won't catch error if you write
```rust
fn main() {
    let a = |x: i32| x;
    let b = a;
    b(1, 2);
}
```

but as a temporary solution I think it's ok

2020-11-16 07:53 UTC, Undin approved these changes
LGTM
Thanks!
Could you squash "fixing" commits into main ones, please?

2020-11-16 15:32 UTC, Undin approved these changes
Thanks!
bors r+

2020-11-16 16:13 UTC, merged