Fix crate version json parsing
intellij-rust/intellij-rust pull request #6818
Opened 2021-02-08 16:57 UTC by avrong

Fixes https://github.com/intellij-rust/intellij-rust/issues/6812
Bug introduced in https://github.com/intellij-rust/intellij-rust/pull/6591

As it turns out, both `Gson` and `Jackson` can't work with inside-function classes.

Citation from https://github.com/FasterXML/jackson-module-kotlin/issues/135:
> It sounds like inner class you use would be non-static (as per exception). Such classes can not be deserialized since there is no access to implicit this reference that would be needed, at least on regular Java. I don't know if Kotlin allows some way make inner class static from JVM perspective; if so, that would make things work fine.

`Gson` is returning `null` in this case without any hint of what could go wrong.

This PR fixes the parsing logic by moving `ParsedVersion` out from the function and uses Jackson as it gives more understandable messages and has better Kotlin support. We might also try to use `kotlinx.serialization` instead, but it may need to have some modifications in Gradle plugins.

In my environment, it now works with no one warning about failed-to-parse versions.

2021-02-08 18:24 UTC, Kobzol commented
Heh, it seemed like an innocent change :) Good catch, thanks.

2021-02-10 18:08 UTC, ortem requested changes

2021-02-10 18:08 UTC, ortem commented on toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
> +    val parsedVersion = ObjectMapper()
Consider using Kotlin module this way:
```Kotlin
    val parsedVersion = JsonMapper()
        .registerKotlinModule()
        .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
        .readValue<ParsedVersion>(json)
```
See `org.rustPerformanceTests.CustomRealProjectAnalysisTest.Companion#data` for example.

2021-02-10 18:08 UTC, ortem commented on toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
> +    @JsonProperty("name") val name: String,
Looks like these annotations are redundant if the Kotlin module is used (see the comment below)

2021-02-10 18:17 UTC, ortem commented
BTW I haven't managed to reproduce the bug, but I faced a different problem:
![bug](https://user-images.githubusercontent.com/4854600/107552913-28bba100-6be5-11eb-9265-33371a157222.gif)

@avrong Is this related to the original issue or JSON parsing?

2021-02-10 18:19 UTC, ortem commented
> Heh, it seemed like an innocent change :)

@Kobzol Yep, and it's a funny thing that I suggested this breaking change in the review actually, sorry for that 😄

2021-02-10 21:25 UTC, avrong commented
@ortem That's interesting. I fixed the problem that the log warnings contained, but now see it is different from the one explained in the issue. Even with the version info parsing problems, there should be no problems with crate names by themselves.

The original problem might be related to @Kobzol case, as he mentioned. But I haven’t managed to reproduce it too.

In your case, version parsing seems to be the problem. You can invalidate caches to force index load from scratch

2021-02-11 17:44 UTC, ortem approved these changes
LGTM. Just to sum up: this **does not** fix https://github.com/intellij-rust/intellij-rust/issues/6812, but anyway, this change is necessary to parse JSON properly. As for https://github.com/intellij-rust/intellij-rust/issues/6812, it should be investigated and fixed in a separate PR.

bors r+

2021-02-11 19:21 UTC, avrong commented
bors r=ortem

2021-02-11 20:10 UTC, merged