INT: Introduce expand dependency specification intention
intellij-rust/intellij-rust pull request #6960
Opened 2021-03-14 13:12 UTC by avrong

Closes #4869

<img width="400" src="https://user-images.githubusercontent.com/6342851/111069568-b76e5700-84de-11eb-931c-25126f832d37.gif">

### TODO
- [ ] Provide TOML intention test-base to perform tests correctly

changelog: Add intention to expand dependency specification in `Cargo.toml`

2021-04-08 16:26 UTC, ortem requested changes

2021-04-08 16:26 UTC, ortem commented on toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
> +        val newKeyValue = TomlPsiFactory(project).createKeyValue("${ctx.key.text} = { version = ${ctx.value?.text ?: "\"\""} }")
Consider introducing variables for readability:
```Kotlin
val crateName = ctx.key.text
val crateVersion = ctx.value?.text ?: "\"\""
```

2021-04-08 16:26 UTC, ortem commented on src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/description.html
> +This intention expands dependency description in Cargo.toml manifest file.
```suggestion
This intention expands dependency specification in Cargo.toml
```

2021-04-08 21:17 UTC, avrong commented on toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
> +        if (table.header.key?.segments?.lastOrNull()?.isDependencyKey != true) return null
There is no need to include table dependencies like `[dependencies.foo]` in the current check

2021-04-09 07:18 UTC, ortem commented on toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
> +        if (table.header.key?.segments?.lastOrNull()?.isDependencyKey != true) return null
I mean this property from `Utils.kt`:
```Kotlin
val TomlTableHeader.isDependencyListHeader: Boolean
       get() = key?.segments?.lastOrNull()?.isDependencyKey == true
```
Looks like `table.header.isDependencyListHeader` would be perfect here, isn't it?

2021-04-09 07:51 UTC, avrong commented on toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
> +        if (table.header.key?.segments?.lastOrNull()?.isDependencyKey != true) return null
Oh, yes. You're right

2021-04-12 09:57 UTC, ortem requested changes

2021-04-12 09:57 UTC, ortem commented on toml/src/main/resources/META-INF/toml-only.xml
> +            <category>Cargo.toml</category>
```suggestion
            <category>Rust/Cargo.toml</category>
```
`<category>Cargo.toml</category>` creates a new category on the top level but this intention should belong to `Rust` instead

2021-04-12 11:06 UTC, ortem approved these changes
bors r+

2021-04-12 12:19 UTC, merged