Take into account CARGO_HOME environment variable in Crates Local Index
intellij-rust/intellij-rust pull request #7411
Opened 2021-06-25 17:29 UTC by avrong

changelog: Take into account the CARGO_HOME environment variable when using crates local index

2021-07-14 10:34 UTC, ortem requested changes
Please handle the situation when `CARGO_HOME` is invalid (e.g. contains a non-existent path). Currently, `LocalFileSystem.getInstance().refreshAndFindFileByPath(cargoRegistryIndexRefsLocation)!!` call (after rebase onto master) leads to `java.lang.NullPointerException` without any user-friendly description

2021-07-14 10:34 UTC, ortem commented on toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
> +        private val cargoRegistryIndexPath
Please specify the type explicitly

2021-07-20 11:05 UTC, avrong commented
I changed how the `CARGO_HOME` environment variable is being retrieved as macOS doesn't bypass them from the shell, so `System.getEnv()` doesn't return any of those. To handle this, IDE calls shell environment on start to get envars using `printenv` and can return them using `EnviromentUtil`

2021-07-22 11:02 UTC, ortem approved these changes
LGTM

2021-07-23 15:40 UTC, ortem commented
bors r+

2021-07-23 18:32 UTC, merged