INT: Support "Invert if condition" without else branch
intellij-rust/intellij-rust pull request #8005
Opened 2021-10-26 15:56 UTC by dima74

![output](https://user-images.githubusercontent.com/6505554/138916115-7d6f98ac-7645-41a8-8057-0d483cccbe9a.gif)

changelog: Support "Invert if condition" without else branch

2021-11-18 17:00 UTC, ortem requested changes
LGTM, I tested the implementation on some real code, and it seems to work very well!
Except for my (mostly minor) comments, I think it's worth describing the implementation in more detail since the logic is quite difficult to understand at first sight. So it would be nice to have some comments inside the code

2021-11-19 12:30 UTC, dima74 commented on src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
> +        val ifStmts: List<PsiElement>,
I would keep `thenBlockStmts` name — there also can be whitespaces/comments, etc, but the core part of this list are statements

2021-11-22 11:27 UTC, ortem approved these changes
LGTM except for one minor comment

2021-11-22 11:27 UTC, ortem commented on src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
> +private fun PsiElement.isLoop(): Boolean =
[minor] Can be replaced by `is RsLooplikeExpr` check

2021-11-22 14:14 UTC, dima74 commented
bors r=ortem

2021-11-23 00:45 UTC, merged