FIX: Resolves #7894
intellij-rust/intellij-rust pull request #8087
Opened 2021-11-08 23:56 UTC by serid

changelog: Add #[repr(...)] quick fix for E0308 error

2021-11-09 00:02 UTC, serid commented
This quick fix was strongly inspired by [this](https://github.com/intellij-rust/intellij-rust/commit/194a0eec911ca7d7f42a7ff99a061ab8762cf259#diff-7b45f27fd09aa0558b2b7cea8f77cf3d243c0cec47ed2f4b019cb18a3b71dd45) commit that added a quick fix for changing function return type.

2021-12-01 03:10 UTC, mchernyavsky requested changes

2021-12-01 03:10 UTC, mchernyavsky commented on src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReprAttributeFixTest.kt
> +    fun `test don't offer fix for aliased types`() = checkFixIsUnavailable(
I'm not sure about this one. Maybe it's better to suggest changing the representation to `u8` in this case?

<img width="609" alt="Screen Shot 2021-12-01 at 06 04 33" src="https://user-images.githubusercontent.com/6079006/144164605-cc04b257-2215-4401-bb51-b1ab60daec99.png">

@Undin What do you think?

2021-12-01 03:10 UTC, mchernyavsky commented on src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReprAttributeFix.kt
> +            if (actualTy.isIntegral && actualTy.aliasedBy == null && findEnumOwner(element) != null)
`findEnumOwner(element) != null` produces a false-positive in this case:

<img width="812" alt="Screen Shot 2021-12-01 at 06 09 04" src="https://user-images.githubusercontent.com/6079006/144164941-316b8bba-2b61-4d3e-b398-008c48d8790d.png">

2021-12-01 03:19 UTC, mchernyavsky commented
I have rebased the branch on master and pushed some minor changes.

2023-04-26 08:31 UTC, vlad20012 approved these changes
bors r+

2023-04-26 09:54 UTC, merged

2023-04-26 09:57 UTC, serid commented
Confratulations, guys! i tried to finish this a few months ago but couldn't run the test suit, glad you got around to it 😄