RUN: support Cargo command debugging from `Run Anything` popup
intellij-rust/intellij-rust pull request #8697
Opened 2022-03-30 10:33 UTC by Undin

Previously, the Cargo and wasm-pack commands invoked from `Run Anything` popup ignored given executor and always use `run` mode
Now, they respect run/debug modes (if possible)

changelog: Respect run/debug modes in [Run Anything](https://www.jetbrains.com/help/idea/running-anything.html) by Cargo commands

2022-03-30 10:35 UTC, Undin commented
Currently, if debugging is not supported for the given command or in the particular IDE, it won't be executed at all. Previously, the plugin always executed any cargo command. @mchernyavsky WDYT about it?

2022-04-04 11:08 UTC, mchernyavsky requested changes
When I tried to debug `cargo --help`, I got this:
```
com.intellij.execution.ExecutionException: Cannot find runner for --help
	at com.intellij.execution.runners.ExecutionEnvironmentBuilder$Companion.create(ExecutionEnvironmentBuilder.kt:48)
	at com.intellij.execution.runners.ExecutionEnvironmentBuilder$Companion.create(ExecutionEnvironmentBuilder.kt:74)
	at com.intellij.execution.runners.ExecutionEnvironmentBuilder.create(ExecutionEnvironmentBuilder.kt)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:159)
	at org.rust.cargo.toolchain.RsCommandLineBase.run(CommandLine.kt:50)
	at org.rust.cargo.toolchain.RsCommandLineBase.run$default(CommandLine.kt:33)
	at org.rust.ide.actions.runAnything.cargo.CargoRunAnythingProvider.run(CargoRunAnythingProvider.kt:29)
	at org.rust.ide.actions.runAnything.RsRunAnythingProvider.execute(RsRunAnythingProvider.kt:69)
	at org.rust.ide.actions.runAnything.RsRunAnythingProvider.execute(RsRunAnythingProvider.kt:27)
	at com.intellij.ide.actions.runAnything.RunAnythingUtil.executeMatched(RunAnythingUtil.java:107)
	at com.intellij.ide.actions.runAnything.RunAnythingPopupUI.executeCommand(RunAnythingPopupUI.java:221)
	at com.intellij.ide.actions.runAnything.RunAnythingPopupUI.lambda$initSearchActions$14(RunAnythingPopupUI.java:717)
	at com.intellij.openapi.project.DumbAwareAction$SimpleDumbAwareAction.actionPerformed(DumbAwareAction.java:80)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

> Currently, if debugging is not supported for the given command or in the particular IDE, it won't be executed at all. Previously, the plugin always executed any cargo command. @mchernyavsky WDYT about it?

I think we should show an error message to a user.

2022-04-04 16:29 UTC, Undin commented
@mchernyavsky I've fixed the exception
Also, I decided to use default run executed if a command can't respect the corresponding mode as it was previously. But now the plugin shows notification about it

2022-04-11 15:22 UTC, mchernyavsky approved these changes
bors r+

2022-04-11 16:50 UTC, merged