ANN: Improve macro highlighter (add more color settings).
intellij-rust/intellij-rust pull request #9033
Opened 2022-07-09 20:04 UTC by daym

This PR adds some new color settings so that macro var bindings can look different to macro var references and those can look different to macro calls.

changelog: Improve macro highlighting

2022-10-21 08:20 UTC, ozkriff requested changes
Hi! Thank you for the PR and sorry for the late review!

I like the general idea of adding more color options to declarative macros but I'd like to propose a few tweaks to the design:

1. I'd really like to use the same colors in the matcher and transcriber parts - after all, this kind of macro is called "macros by example" and it feels like losing the symmetry may really confuse the users.
2. It's definitely a good idea to give metavariables their own color instead of re-using FUNCTION but I think they should be highlighted with it in the matcher part too to stand out from the pattern.
3. I don't have a strong opinion here but do we really need the option to highlight repetitions ("groups")? It feels to me that the basic highlighting of macro-specific machinery is already enough to make it quite noticeable.
4. The current user-visible naming is based on ijrust's internals and not terminology from rust book/reference, it may be a bit confusing to users.

So, as I see it, it'd be good to have:

- "Macros/Macro" - a general baseline macro color used for all the machinery (including the transcriber parts), same as the old "Macro".
- "Macros/Macro calls" - a new color for calls that has the default value of "Macros/Macro".
- "Macros/Metavariable" - a completely new color for metavariable identifiers. Maybe it should default to IDENTIFIER.
- "Macros/Repeating" (?) - a new color for $()? stuff (if we decide to keep it).

The new colors also need to be set in `resources/org/rust/ide/colors/RustDefault.xml` (and `RustDarcula.xml`) schemes.

@vlad20012 @undin do you have any thoughts on all this?

2022-11-06 00:44 UTC, daym commented
>I'd really like to use the same colors in the matcher and transcriber parts - after all, this kind of macro is called "macros by example" and it feels like losing the symmetry may really confuse the users.

Changed.

>It's definitely a good idea to give metavariables their own color instead of re-using FUNCTION but I think they should be highlighted with it in the matcher part too to stand out from the pattern.

Aren't they highlighted already with this changeset? Seems to work for me.

>I don't have a strong opinion here but do we really need the option to highlight repetitions ("groups")? It feels to me that the basic highlighting of macro-specific machinery is already enough to make it quite noticeable.

In general, I'd like the highlighting to allow the user do see which input characters go to the output unchanged, and which are part of the macro machinery. The rest is not so important to me.

What I do not want is `$(` to look the same as `(` as a literal paren, and especially `)` of the former to look the same as `)` as a literal paren. That would be very bad.

>"Macros/Macro" - a general baseline macro color used for all the machinery (including the transcriber parts), same as the old "Macro".
>"Macros/Macro calls" - a new color for calls that has the default value of "Macros/Macro".

Not sure where this is used in the end. Right now, it's mostly marking the keyword `macro_rules`.

>"Macros/Metavariable" - a completely new color for metavariable identifiers. Maybe it should default to IDENTIFIER.

Done

>"Macros/Repeating" (?) - a new color for $()? stuff (if we decide to keep it).

Done

>The new colors also need to be set in resources/org/rust/ide/colors/RustDefault.xml (and RustDarcula.xml) schemes.

Not done yet since I have no idea what the keys in that file mean. What are they now in the newly changed changeset?

2023-02-17 19:43 UTC, daym commented
ping?

2023-08-14 10:17 UTC, daym commented
ping

2026-09-09 20:10 UTC, closed without merging