DBG: Update MSVC pretty-printers and type name decorators to Rust 1.67
intellij-rust/intellij-rust pull request #9965
Opened 2023-01-12 16:04 UTC by ortem

Fixes #7935.
Fixes #9769.

changelog: Update debugger pretty-printers and type name decorators for MSVC to Rust 1.67. Now the debugger renders `str` and slice types properly

2023-01-30 19:37 UTC, Undin requested changes
@ortem since #9962 is already merged, could you rebase changes onto master?

2023-01-30 20:33 UTC, ortem commented
@Undin Rebased onto master

2023-02-03 13:53 UTC, Undin reviewed
Works for me me but comments

2023-02-03 13:53 UTC, Undin commented on debugger/src/main/kotlin/org/rust/debugger/lang/RsMSVCTypeNameDecoratorVisitor.kt
> +            builder.append("]")
Maybe extract `ctx.type.msvcTypeName()` into variable since we use them 3 times?

2023-02-03 13:53 UTC, Undin commented on debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt
> +        "ptr_const$<str>",
Is it possible to get this combination at all?
It seems it was just `str` previously and now it is `ptr_const$<str$>`

2023-02-03 15:12 UTC, Undin commented on debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt
> +        "ptr_const$<str>",
It's possible

2023-02-03 15:12 UTC, Undin approved these changes

2023-02-03 15:28 UTC, ortem commented
bors r=Undin

2023-02-03 15:29 UTC, ortem commented
bors r-

2023-02-03 15:32 UTC, ortem commented
bors r+

2023-02-03 17:58 UTC, merged